export default function TesPost() {
    return (
        <section className="flex flex-col gap-5">
            <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Eveniet nesciunt saepe numquam, iusto, repellendus culpa velit doloremque sunt blanditiis nihil explicabo. Nulla corporis, veritatis assumenda ullam, rerum obcaecati autem doloremque accusantium voluptatum dolorum tempora? Repellendus nam nostrum recusandae exercitationem nobis quasi earum obcaecati ducimus, delectus commodi iure qui officiis asperiores laborum neque aliquid ipsa illo ratione eius nesciunt. Rerum fugiat aliquam officia, nostrum pariatur dolorum, asperiores veritatis, tempore atque nihil error sint quae provident consequatur! Natus fugiat perferendis obcaecati deserunt autem error praesentium a sint facere vel atque at molestiae hic earum adipisci, dignissimos, itaque optio! Aspernatur labore quis ad!</p>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quasi commodi, nostrum omnis ipsam animi nesciunt. In, sed repellendus temporibus corrupti, voluptas sequi soluta minus eligendi ut hic blanditiis! Iure rerum, ipsam repudiandae blanditiis accusamus tempora placeat, eius modi voluptatibus asperiores perspiciatis repellat deserunt adipisci porro explicabo et! Nulla consectetur magni, a blanditiis iure earum, odit animi beatae quod hic, iste unde repudiandae illum mollitia! Sequi esse minima voluptate at vitae debitis quaerat unde consectetur in.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Similique laboriosam dolor, corporis cupiditate dolorem deleniti vel fugit qui aspernatur voluptatem suscipit eos ipsum eum fugiat optio sed incidunt architecto consequuntur ullam. Nam deserunt reiciendis doloremque, eligendi sed excepturi cumque eaque officiis architecto accusantium eos pariatur harum laboriosam distinctio ducimus perferendis nihil blanditiis a! Repellendus ipsam error vitae perspiciatis hic. Consequatur fugiat, odio maiores ratione ea iste alias voluptas culpa saepe aspernatur incidunt dolores fugit magnam optio a minus omnis, mollitia aliquid unde! Excepturi optio veritatis id blanditiis doloribus eligendi quos ea iste amet maxime, enim rem quas ratione sed eius sint ad doloremque autem illo quis ducimus, unde fugiat assumenda? Tenetur blanditiis voluptate vero fugiat nobis! Aliquid quia ducimus, excepturi deserunt dicta fuga rerum ratione?</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Qui reiciendis eligendi quas beatae fugit, molestias voluptatem ex expedita ut! Aperiam.</p>
        </section>
    )
}